# name: Trigger All Git Flow from PR Comment

# on:
#     issue_comment:
#         types: [created]

# jobs:
#     run-all:
#         if: github.event.issue.pull_request != null && (startsWith(github.event.comment.body, '/run-all'))
#         runs-on: ubuntu-latest

#         steps:
#             - uses: actions/checkout@v4

#             - name: Set up Python
#               uses: actions/setup-python@v4
#               with:
#                   python-version: 3.11

#             - name: Install Dependencies
#               run: |
#                   python -m pip install -U pip
#                   python -m pip install -r ./azure/requirements.txt

#             - name: Run Linting on Azure Directory
#               run: |
#                   python -m isort ./azure --profile=black --check
#                   python -m black ./azure --check
#                   python -m flake8 ./azure --ignore=E203,E231,E266,E501,W503

#             - name: Run MyPy on Azure directory
#               run: python -m mypy ./azure --strict

#             - name: Install ODBC Driver 18 for SQL Server
#               run: |
#                   curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
#                   curl -fsSL https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
#                   sudo apt-get update
#                   sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
#                   sudo apt-get install -y unixodbc-dev

#             - name: Run PyTest on Azure directory
#               env:
#                   FUNCTIONS_WORKER_RUNTIME: ${{ secrets.FUNCTIONS_WORKER_RUNTIME }}
#                   AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
#                   AzureWebJobsFeatureFlags: ${{ secrets.AzureWebJobsFeatureFlags }}
#                   AzureWebJobsStorage: ${{ secrets.AzureWebJobsStorage }}
#                   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#                   DBHOST: ${{ secrets.DBHOST }}
#                   DBNAME: ${{ secrets.DBNAME }}
#                   DBUSER: ${{ secrets.DBUSER }}
#                   DBPASS: ${{ secrets.DBPASS }}
#                   QUICKSCRAPER_TOKEN: ${{ secrets.QUICKSCRAPER_TOKEN }}
#               run: python -m pytest ./azure
