name: Trigger All Git Flow from PR Comment

on:
    issue_comment:
        types: [created]

jobs:
    run-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: echo "branch name ${{ github.event.pull_request.base.ref }}"
            - uses: echo "branch name ${{ github.event.pull_request.base.label }}"
