name: Trigger All Git Flow from PR Comment

on:
    issue_comment:
        types: [created]

jobs:
    run-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            # - uses: octokit/request-action@v2.x
            #   id: branch-name
            #   with:
            #       route: GET /repos/{owner}/{repo}/pulls/${{ github.issue.number }}
            #       owner: carlo-setldpay
            #       repo: SampleWorkflow
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # - run: "echo latest release: '${{ steps.branch-name..data }}'"
            - id: sample
              run: |
                  GITHUB_PR_RECORD=$(curl -L \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number}}")
                echo data=$GITHUB_PR_RECORD >> "$GITHUB_OUTPUT"
            - run: echo "${{ fromJSON(steps.sample.outputs.data).head.ref }}"
            - run: echo "${{ fromJSON(steps.sample.outputs.data).base.ref }}"
            - run: echo "${{ steps.sample.outputs.data }}"
