name: Trigger All Git Flow from PR Comment

on:
    issue_comment:
        types: [created]

jobs:
    run-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get branch names.
              id: branch-names
              uses: tj-actions/branch-names@v8
            - run: echo "${{ toJSON(steps.branch-names.outputs) }}"
            - run: echo "branch name ${{ toJSON(github) }}"
            - run: |
              echo "branch name ${{ github.base_ref }}"
            - run: echo "branch name ${{ github.action }}"
            - run: echo "branch name ${{ github.action_path }}"
