name: Sample 

on:
    [workflow_dispatch]

jobs:
    run-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "github run_id:\\${{ github.run_id }}"
            - run: echo "github run_number:\\${{ github.run_number }}"
            - run: echo "github run_attempt:\\${{ github.run_attempt }}"